# Generated by Django 6.0.5 on 2026-05-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age_months',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='daily_calorie_goal',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='pets.pet')),
            ],
        ),
    ]
